
HOST_RESOURCE_IDENTIFIER = 'host'
UNASSIGNED_ROOM_NAME = 'unassigned'
DECOMMISSION_ROOM_NAME = 'decommission'

COMMON_CLIENT_MAX_RECONNECT_INTERVAL_SECS = 30

WORKER_DEFAULT_ROOM_CHECK_INTERVAL_SECS = 5